### ISSUE TITLE
getUnitedStates seems redundant

### ISSUE THREAD

**Issue by toddheslin** [carlaiau/flatten-the-curve#27]
Just noticed this:

https://github.com/carlaiau/flatten-the-curve/blob/master/processing/get.js#L635L639

It seems that the `getUnitedStates()` function is redundant as it's not running with any `json_data`.

Let me know how this was set up and I'll send a PR with the appropriate changes.

**Comment by carlaiau** [comment]
@toddheslin getUnitedStates is still been used, it just looks like I have left it to run by default when the script isn't passed any arguments from earlier testing.

GetUnitedStates restructures that data from this endpoint https://covidtracking.com/api/states/daily

**Comment by toddheslin** [comment]
Sweet, will tidy up. I've kinda bitten of a big chunk and going to suggest a reformatting of the `get.js` processor. I think it should make it easier to extend the processing as more sources come in. Will see how much I get done tonight, currently on a chocolate high 🍫 🐇

**Comment by carlaiau** [comment]
Yesssss, awesome stuff man! It is very messy at the moment
